### ISSUE TITLE
Spring 2 Backlog - Expand Content

### ISSUE THREAD

**Issue by msami444** [msami444/IT115Assignment5#9]
- [x]  Add introductory section on homepage. #16 
- [x]  Add content to lakes.html, falls.html #11 #10 
- [ ]  Add About Us/Essential Information Section #
- [x]  Add contact information and park hours (add to footer) #18
